import { Link } from 'react-router-dom'

export default function NearbyShare() {
  return (
    <section className="mx-auto w-full max-w-4xl px-4 py-16 md:px-6 text-center space-y-10 animate-fadeIn">
      
      {/* Intro Header */}
      <div className="space-y-4 max-w-xl mx-auto">
        <div className="inline-flex items-center gap-1.5 rounded-full bg-cyan-500/10 dark:bg-cyan-400/15 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.2em] text-cyan-600 dark:text-cyan-300 border border-cyan-500/20">
          ⚡ Nearby Sharing
        </div>
        
        <h1 className="text-4xl font-black text-slate-900 dark:text-white tracking-tight">
          Quick Local Transfer
        </h1>
        
        <p className="text-slate-650 dark:text-slate-350 text-base leading-relaxed">
          Share files easily with nearby devices on your local network. No lengthy link sharing—just pair with a simple 4-digit code.
        </p>
      </div>

      {/* Grid Selection */}
      <div className="grid gap-6 md:grid-cols-2 max-w-2xl mx-auto">
        
        {/* Send Option Card */}
        <Link
          to="/send?mode=nearby"
          className="hover-lift flex flex-col items-center justify-center p-8 rounded-[28px] border border-slate-200 bg-white/70 shadow-md hover:border-indigo-500/30 hover:shadow-indigo-500/5 transition duration-300 dark:border-slate-800 dark:bg-slate-900/50 group text-center relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.04),transparent_50%)]" />
          
          <div className="p-4.5 rounded-2xl bg-indigo-500/10 text-indigo-500 group-hover:scale-110 transition duration-300 relative z-10">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="w-8 h-8">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 19.5v-15m0 0l-6.75 6.75M12 4.5l6.75 6.75" />
            </svg>
          </div>
          
          <h2 className="text-lg font-bold text-slate-800 dark:text-white mt-6 relative z-10">Send Nearby</h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 relative z-10 leading-relaxed">
            Queue up files and generate a local 4-digit pairing room code for others.
          </p>
        </Link>

        {/* Receive Option Card */}
        <Link
          to="/receive?mode=nearby"
          className="hover-lift flex flex-col items-center justify-center p-8 rounded-[28px] border border-slate-200 bg-white/70 shadow-md hover:border-cyan-500/30 hover:shadow-cyan-500/5 transition duration-300 dark:border-slate-800 dark:bg-slate-900/50 group text-center relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(6,182,212,0.04),transparent_50%)]" />

          <div className="p-4.5 rounded-2xl bg-cyan-500/10 text-cyan-500 group-hover:scale-110 transition duration-300 relative z-10">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="w-8 h-8">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
            </svg>
          </div>
          
          <h2 className="text-lg font-bold text-slate-800 dark:text-white mt-6 relative z-10">Receive Nearby</h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 relative z-10 leading-relaxed">
            Enter a 4-digit code generated by a nearby device to join and download files.
          </p>
        </Link>
      </div>
    </section>
  )
}
